language: php
php:
  - 7.2
  - 7.1
  - 7.0

dist: trusty
sudo: false

services:
  - redis-server

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - wkhtmltopdf
      - xvfb

before_install:
  - mysql -h localhost -V
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - composer install --prefer-source --no-interaction
  - php infuse migrate
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

env:
  global:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - INFUSE_ENV=test
    - WKHTMLTOPDF_CMD="xvfb-run --server-args='-screen 0, 640x480x16' --wait=0 --auto-servernum --server-num=1 wkhtmltopdf --print-media-type --disable-javascript  --disable-local-file-access --allow file:///usr/share/fonts/TTF/Arial-Unicode.ttf --margin-top 0.5cm --margin-left 0.5cm --margin-right 0.5cm --margin-bottom 2cm -s letter --encoding utf8 -q - -"

notifications:
  email: false